apiVersion: v1
kind: Service
metadata:
  name: serve
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: server-serving-certs
spec:
  selector:
    app: serve
  ports:
  - name: https
    port: 8080
    protocol: TCP
    targetPort: 8080
