/*Entry point for snapshot process

Snapshot will query bugzilla (and trello) and then will attempt to store the
data into a postgresql database.  The data will be inserted with a datestamp
that pairs with the id to make a primary key.  Snapshot will remove any
previous data from today and insert the new data in a single transaction.  This
means there will always be a single snapshot per day.

This is intended to be run as a cron job in OpenShift - however it can also be
run locally. It is assumed that a postgresql database exists where the relevant
tables have been created.

*******************************************************************************

When running on OpenShift, the config file with the credentials and other
variables will need to be mounted at /etc/internal-tools/snapshot_cfg.yaml .
The hostname will default to the postgresql service that is created when using
the standard postgresql container. Likewise, the environment variables that
are generated by the postgresql container need to be injected into the snapshot
pod.

It is recommended to snapshot once per hour if you need up-to-date data for
today.  We want to snapshot the state at the same time every day to get
accurate data that can be easily compared.  The default cron job will run once
per hour from 0600 - 2000.  Only the latest snapshot per day is kept, so our
database will have snapshots from everyday at 2000 to provide a history to
analyze.

schedule: '0 6-20 * * *'

*******************************************************************************

When running locally, the config file with any credentials/config variables
and the database hostname will need to be passed in as command line arguments.
You will also need to export the following environment variables to provide
the necessary information to access the database. These variables mimic those
used with the standard postgresql container.

export POSTGRESQL_USER="myusername"
export POSTGRESQL_PASSWORD="mypassword"
export POSTGRESQL_DATABASE="mydatabasename"

go run cmd/snapshot/main.go cmd/snapshot/options.go -c /path/to/snapshot_cfg.yaml -h localhost
*/
package main
